### ISSUE TITLE
Feature Suggestion: Locked Compact Machines

### ISSUE THREAD

**Issue by Badcholo** [thraaawn/CompactMachines#123] opened 2015-05-16 15:07 UTC
To be able to lock a compact machine and not allow other players to break/destroy the block by any means. Also Restricts and allows access to set players. This will allow players to create a base that is protected from raids and also live with other players and share / restrict resources. There can be a Access and a Break/Destroy Block. Also maybe a Officer, Owner, Member Access Restrict. Again, it can be simple first such as don't break/destroy Personal Access only. Config option for players that don't want this feature. I like how your able to create a "Hive" or network of rooms that can go on forever, This mod is amazing.

**Comment by Badcholo** [comment] 2015-05-16 15:13
Players love this mod since now they don't have to build their homes at y4 and deal with fog, or be threatened by players using xray. This is turning out to be a great protection mod. players can't just glitch thru walls to get into your base.

**Comment by thraaawn** [comment] 2015-05-18 08:31
Duplicate of #102

**Closed by thraaawn** 2015-05-18 08:31 UTC

**Comment by Badcholo** [comment] 2015-05-18 14:24
of course.. sorry. i thought it was different.
