### ISSUE TITLE
server crash when entering cube, seems related to AE2

### ISSUE THREAD

**Issue by nightstalker6669** [thraaawn/CompactMachines#106] opened 2015-04-21 19:58 UTC
http://pastebin.com/Mc1t7Hh4

using cauldron 1370 (yes keep world loaded is enabled) and build compactmachines-1.7.10-1.19-fluids-preview-b14

AE2 rv2-beta 27

**Comment by XFactHD** [comment] 2015-04-25 22:46
Even though AE2 doesn't have storage cells and other network blocks for fluids (except the p2p tunnel), it has a built-in storage handler for fluids. This means that AE2 uses the forge fluid system, which has changed in the latest forge. I think that AE2 is not compiled against the newest forge because most of the popular mods are still using the old system. Am I right @thatsIch?

**Comment by thatsIch** [comment] 2015-04-26 07:43
You are correct, we were told, that it is broken somehow. Since we do not much with fluids, we basically ignored it, but this error is generated due to 

    Caused by: java.lang.ClassNotFoundException: vazkii.botania.api.mana.IManaPool

So it seems, you using a hard dependency on it or not stripping the API correctly.

**Comment by thraaawn** [comment] 2015-04-26 11:12
Fixed with 3b56032cb4ccc679c22744dfd00a27a4b97255da

**Closed by thraaawn** 2015-04-26 11:12 UTC
