### ISSUE TITLE
Compact Machines won't Auto-Chunkload

### ISSUE THREAD

**Issue by Selim042** [thraaawn/CompactMachines#141] opened 2015-06-24 16:45 UTC
I have my AE network based in a Compact Machine, and I then run it out the floor to get it to my base, though after updating my modpack, anything outside of the machine will not connect to the system.

Compact Machines 1.19b
Applied Energistics 2 rv2 stable 9

**Comment by Selim042** [comment] 2015-06-25 11:53
While watching the server shutdown, saw this message: "Unable to lookup CompactMachines:interfaceblock for public static org.dave.CompactMachines.block.BlockCM org.dave.CompactMachines.init.ModBlocks.interfaceblock. Is there something wrong with the registry?".  Might this have something to do with it?

**Comment by Selim042** [comment] 2015-06-25 12:47
Upon further testing, it appears the Compact Machine chunk loading is not working.

**Comment by thraaawn** [comment] 2015-07-04 15:21
I cannot reproduce this issue. Check your configuration for the used chunk loading mode.
It also sounds a bit like you expect the chunk in the overworld where the CM is located to be loaded - it won't be, only the inside of Compact Machines is being loaded by the mod.

**Comment by Selim042** [comment] 2015-07-05 03:46
The inside of my machine isn't being loaded, and the config is set to always load them.

**Comment by RaineAndrews** [comment] 2016-06-21 16:21
Selim, are you using The Ferret Business modpack?  I'm having similar issues with the compact machine not chunk loading.  My ore tripling is ore null right now.  Adding a chunk loading to the outside didn't help.  Adding a chunk loader to my compact machine fixes this issue.

**Comment by RaineAndrews** [comment] 2016-06-21 16:56
I did some more tinkering, and my numbers don't match up, its like finished product disappears from my mekanism build.  Since I have chunk loaders both inside and outside the machine, perhaps its a transportation issue?

**Comment by RaineAndrews** [comment] 2016-06-21 17:06
I'm currently at ore tripling, and I'm always off by a multiple of 3.  I feed the machine from the outside.  Maybe the machine is importing it incorrectly some of the time and it loses the ore into the void :(

**Comment by Selim042** [comment] 2016-06-22 01:39
You do realize that this issue is from almost a year ago?

**Comment by RaineAndrews** [comment] 2016-06-22 02:07
Should I open a new issue.  This one was never closed and I have similar issues...

**Comment by Selim042** [comment] 2016-06-22 14:10
Well, are you using the same versions?  If so, it still applies, if not, it is up to you.  I'm just saying that if an issue was never closed for almost a year, chances are that the issues aren't being looked at.

**Comment by thraaawn** [comment] 2017-02-27 13:35
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.

**Closed by thraaawn** 2017-02-27 13:35 UTC
Labels: question
