### ISSUE TITLE
Entering/leaving machine deletes xp levels

### ISSUE THREAD

**Issue by boundingstar** [thraaawn/CompactMachines#164] opened 2016-01-07 01:06 UTC
I am using the obscurity pack, so it may be a conflict, but when entering or leaving a compact machine, the player's xp levels are removed or set back to 0.

**Comment by Maxiride** [comment] 2016-02-11 17:46
It happens to me too using a custom modpack. I guess it's CM itself the cause.

**Comment by Badcholo** [comment] 2016-02-11 19:37
have you tried just changing dimensions like going to the nether or end? See if your xp changes when that happens.

**Comment by XFactHD** [comment] 2016-02-12 07:16
This is a bug in vanilla caused by not sending a packet to resync the xp level.

**Comment by Maxiride** [comment] 2016-02-12 11:48
@Badcholo for me it happens only when entering the CM dimension. Nether, Aroma dimensional world, Aether, Deep Dark, Last Millennium etc works fine.

Since I use a custom modpack it's not a bid deal this issue, there are items from other mods that store you xp into tanks or items.

**Comment by thraaawn** [comment] 2017-02-27 13:28
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.

**Closed by thraaawn** 2017-02-27 13:28 UTC
