### ISSUE TITLE
Crash on NEI recipe

### ISSUE THREAD

**Issue by Corvorosso** [thraaawn/CompactMachines#160] opened 2015-11-30 00:49 UTC
my client crash when I open a NEI recipe with your last build 1.21
on the crash log i see some error on rotarycraft by reika

complete crash log

http://pastebin.com/CrRtXQgn

**Comment by Badcholo** [comment] 2015-11-30 10:34
Is this in SSP or SMP. This happens to me when the server and client do not have matching config files.

**Comment by Corvorosso** [comment] 2015-11-30 14:00
Single player

**Comment by adamcogx** [comment] 2015-12-01 02:40
The problem is caused by NEI Integration (I tested with 1.0.13).  At least in my install.

**Comment by ktole1999** [comment] 2016-02-12 16:56
v13 has moved alot of recipe handling out. try v12. i ran into this with forestry as well as pams harvest. would crash client doing recipe lookup.

**Comment by thraaawn** [comment] 2017-02-27 13:33
Currently working on a 1.10.2 version, the 1.7.10 version is not being maintained anymore, sorry.
Closing all issues not relevant for the new version.

**Closed by thraaawn** 2017-02-27 13:33 UTC
